// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types/contract.proto

package types // import "github.com/zhigui-projects/zwasm/types"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CallInfo struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Args                 [][]byte `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CallInfo) Reset()         { *m = CallInfo{} }
func (m *CallInfo) String() string { return proto.CompactTextString(m) }
func (*CallInfo) ProtoMessage()    {}
func (*CallInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_contract_5beb93a078f50643, []int{0}
}
func (m *CallInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallInfo.Unmarshal(m, b)
}
func (m *CallInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallInfo.Marshal(b, m, deterministic)
}
func (dst *CallInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallInfo.Merge(dst, src)
}
func (m *CallInfo) XXX_Size() int {
	return xxx_messageInfo_CallInfo.Size(m)
}
func (m *CallInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CallInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CallInfo proto.InternalMessageInfo

func (m *CallInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CallInfo) GetArgs() [][]byte {
	if m != nil {
		return m.Args
	}
	return nil
}

func init() {
	proto.RegisterType((*CallInfo)(nil), "types.CallInfo")
}

func init() { proto.RegisterFile("types/contract.proto", fileDescriptor_contract_5beb93a078f50643) }

var fileDescriptor_contract_5beb93a078f50643 = []byte{
	// 138 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x29, 0xa9, 0x2c, 0x48,
	0x2d, 0xd6, 0x4f, 0xce, 0xcf, 0x2b, 0x29, 0x4a, 0x4c, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0x62, 0x05, 0x8b, 0x2a, 0x19, 0x71, 0x71, 0x38, 0x27, 0xe6, 0xe4, 0x78, 0xe6, 0xa5, 0xe5,
	0x0b, 0x09, 0x71, 0xb1, 0xe4, 0x25, 0xe6, 0xa6, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81,
	0xd9, 0x20, 0xb1, 0xc4, 0xa2, 0xf4, 0x62, 0x09, 0x26, 0x05, 0x66, 0x0d, 0x9e, 0x20, 0x30, 0xdb,
	0x49, 0x23, 0x4a, 0x2d, 0x3d, 0xb3, 0x24, 0xa3, 0x34, 0x49, 0x2f, 0x39, 0x3f, 0x57, 0xbf, 0x2a,
	0x23, 0x33, 0xbd, 0x34, 0x53, 0xb7, 0xa0, 0x28, 0x3f, 0x2b, 0x35, 0xb9, 0xa4, 0x58, 0xbf, 0xaa,
	0x3c, 0xb1, 0x38, 0x57, 0x1f, 0x6c, 0x7a, 0x12, 0x1b, 0xd8, 0x2e, 0x63, 0x40, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x9f, 0xd6, 0xba, 0x6f, 0x83, 0x00, 0x00, 0x00,
}
